# Play-01
- name: play-01
  hosts: web
  tasks: 
  - name: play-01 task-01
    ansible.builtin.debug:
      msg: "This is from paly-01 and task-01"

# Play-02 --> usually we write one play in one paly book.
- name: play-02
  hosts: web
  tasks: 
  - name: play-02 task-01
    ansible.builtin.debug:
      msg: "This is from paly-02 and task-01"
