- name: devops course information
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS"
    duration: 120
    topics:
    - linux
    - shell
    - ansible
    - terraform
    - aws
    - k8
    live: true
    tools: # map / dictionary (key:value pairs)
      ci: jenkins # string
      cm: ansible
      cloud: aws
      aws:
      - IAM
      - S3
  tasks:
  - name: Print the course information
    ansible.builtin.debug:
      msg: "Hi I am learing {{course}}, with {{duration}} hrs of duration, the topics are {{topics}}, live: {{live}}, tools are {{tools}}"
