- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}" # here item is reserved key word
    loop:
    - Ram
    - Raheem
    - Robert


