- name: Demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: Print the default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

  - name: Convert to upper case
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

  - name: Convert to lower case
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"
      