- name: Demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: Print the default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

  - name: Convert to upper case
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

  - name: Convert to lower case
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

  - name: find the unique values
    vars:
      numbers: [1,2,3,2,5,1,6]
    ansible.builtin.debug:
      msg: " Unique values are {{ numbers | unique }}"

  - name: Find max number
    vars:
      numbers: [1,2,3,2,5,1,6]
    ansible.builtin.debug:
      msg: " Max number is {{ numbers | max }}"

  - name: Find min number
    vars:
      numbers: [1,2,3,2,5,1,6]
    ansible.builtin.debug:
      msg: " Min number is {{ numbers | min }}"