- name: Command vs Shell
  hosts: local
  connection: local
  tasks:
  - name: Execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output

  - name: check the process # "ps -ef | grep ssh" will not work with command module, it will work with shell
    ansible.builtin.command: ps -ef | grep ssh
    register: output 
